name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.24"

    - name: Sync Go Workspace
      run: go work sync

    - name: Run API unit tests
      run: go test ./api/internal/handler -v

    - name: Run User‐Service unit tests
      run: go test ./user-service/internal/... -v
